// Register your apis here

import '../../api/links/methods.js'
import '../../api/links/server/publications.js'
import '../../api/customers/methods.js'
import '../../api/customers/server/publications.js'
import '../../api/products/methods.js'
import '../../api/products/server/publications.js'
import '../../api/smaps/methods.js'
import '../../api/smaps/server/publications.js'
import '../../api/accounts/server/publications.js'
import '../../api/members/server/publications.js'
import '../../api/visits/methods.js'
import '../../api/visits/server/publications.js'
import '../../api/visitnotes/methods.js'
import '../../api/visitnotes/server/publications.js'
import '../../api/definitions/server/publications.js'
import '../../api/chats/methods.js'